services:
  db:
    container_name: aeco-db
    image: postgres:12.19
    ports:
      - "5434:5432"
    env_file:
      - .env
    volumes:
      - aeco-db-data:/var/lib/postgresql/data
    networks:
      - net-aeco

  backend:
    container_name: aeco-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    devices:
      - "/dev:/dev"
    ports:
      - "3333:3333"
    privileged: true
    sysctls:
      - net.ipv4.ip_unprivileged_port_start=0
    cap_add:
      - SYS_ADMIN
    env_file:
      - ./backend/.env
    depends_on:
      - db
    networks:
      - net-aeco
    volumes:
      - ./backend:/app
      - /dev:/dev

  frontend:
    container_name: aeco-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - net-aeco

  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - net-aeco
  
  adminer:
    container_name: adminer
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - net-aeco

volumes:
  aeco-db-data:
  portainer_data:

networks:
  net-aeco:
    external: true
